name: Check for ESLint Errors

on: [pull_request]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install NPM Dependencies
        run: |
          rm -rf node_modules/
          yarn install --frozen-lockfile

      - name: Run ESLint
        run: |
          yarn run lint
